### ISSUE TITLE
Destructuring with implicit parameters

### ISSUE THREAD

**Issue by SoaringEarth** [nh7a/Geohash#1]
These appear when building in xcode beta 9

<img width="1165" alt="screen shot 2017-06-16 at 08 11 37" src="https://user-images.githubusercontent.com/3295039/27215952-87c26018-526b-11e7-998f-33ba56004303.png">

**Comment by nh7a** [comment]
That's right. I pushed some adjustments to branch https://github.com/nh7a/Geohash/tree/swift4

**Comment by nh7a** [comment]
This is no longer the case with Xcode 9 beta 4.
