### ISSUE TITLE
How to get coordinates of  Rectangle when decoding Geohash

### ISSUE THREAD

**Issue by itsviral** [nh7a/Geohash#4]
When we decode the Geohash . We get two coordinates. I am confused with terms Max and Min that applies to coordinates. 
Is it possible to have 4 coordinates instead of 2 so we can draw rectangle like [Movable Script example](http://www.movable-type.co.uk/scripts/geohash.html). 
How can we find neighbours of geohash ?
Thanks

**Comment by nh7a** [comment]
Although they may not be the best names, they are not two coordinates but two _ranges_; latitude range and longitude range.
```swift
let gbsuv = Geohash.decode(hash: "gbsuv")!
let coords = [
  CLLocationCoordinate2DMake(gbsuv.latitude.min, gbsuv.longitude.min),
  CLLocationCoordinate2DMake(gbsuv.latitude.max, gbsuv.longitude.min),
  CLLocationCoordinate2DMake(gbsuv.latitude.max, gbsuv.longitude.max),
  CLLocationCoordinate2DMake(gbsuv.latitude.min, gbsuv.longitude.max),
]
let polygon = MKPolygon(coordinates: coords, count: coords.count)
```

Maybe adding a utility function to find neighbors is a good idea while you can find it like below for now.
```swift
CLLocationCoordinate2DMake(gbsuv.latitude.max.nextUp,
                           gbsuv.longitude.min).geohash(length: 5)  // gbsvj
CLLocationCoordinate2DMake(gbsuv.latitude.min.nextDown,
                           gbsuv.longitude.min).geohash(length: 5)  // gbsut
```

**Comment by itsviral** [comment]
This is really helpful. I will make utility function to find rest 6 neighbours. Thank you
