### ISSUE TITLE
Use canImport(CoreLocation)

### ISSUE THREAD

**Issue by kengruven** [nh7a/Geohash#6]
Right now, at the end of Geohash.swift, it does something like this:

    #if os(OSX) || os(iOS)
    import CoreLocation
    ...
    #endif

As of Swift 4.1, there's a new way to achieve this that doesn't require us to hardcode a list of operating systems:

    #if canImport(CoreLocation)
    import CoreLocation
    ...
    #endif

This would allow the CLLocationCoordinate2D extensions to work on other platforms, like tvOS and watchOS and any future OSs that happen to implement this.

**Comment by nh7a** [comment]
Thanks @kengruven, fixed.
